# Generated by Django 3.2.9 on 2021-12-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiko', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
