# Generated by Django 3.2.9 on 2021-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.TextField(),
        ),
    ]
