# Generated by Django 3.2.9 on 2021-12-19 09:24

from django.db import migrations, models
import tiko.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiko', '0002_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=tiko.models.product_image_directory),
            preserve_default=False,
        ),
    ]
